### ISSUE TITLE
更换博客的评论系统 | ingbyr

### ISSUE THREAD

**Issue by ingbyrtk** [ingbyrtk/blog-comment-plugin#1]
http://www.ingbyr.com/2017/07/10/change-comment-sys/

**Comment by ingbyrtk** [comment]
Gitment test

**Comment by ingbyrtk** [comment]
# Markdown Test
> Hello
Have a nice day

**Comment by ingbyr** [comment]
Eye

**Comment by xCss** [comment]
![image](https://user-images.githubusercontent.com/10877162/33108473-3fcb6bfe-cf77-11e7-883c-c644a479270b.png)

`Just Test`

and Recommend [Valine](https://valien.js.org)
